[tools]
python = "3.13.13"
gcloud = { version = "latest", depends = ["python"], post_install = '''
    $CLOUDSDK_PYTHON --version
    ''' }

[env]
CLOUDSDK_PYTHON = { value = "{{ tools.python.path | default(value='') }}/bin/python3", tools = true }
