name: ci

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  before-fix-together:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: 2026.6.9 # [default: latest] mise version to install
          install: false
          cache: false
          experimental: true
          log_level: debug
      - run: |
          echo "Before $CLOUDSDK_PYTHON"
          mise install
          echo "After $CLOUDSDK_PYTHON"
