name: install-together

on:
  workflow_dispatch:
  pull_request:
  push:
    tags: ["*"]
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  MISE_EXPERIMENTAL: true

jobs:
  install-together:
    name: "install-together mise:${{ matrix.version }}"
    runs-on: bookworm-slim
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        version:
          - "2026.6.9"
          - "2026.6.10"
    steps:
      - uses: actions/checkout@v6
      - uses: jdx/mise-action@v3
        with:
          version: ${{ matrix.version }} # [default: latest] mise version to install
          install: false
          cache: false
          experimental: true
          log_level: debug
      - run: |
          echo "Before $CLOUDSDK_PYTHON"
          mise install
          echo "After $CLOUDSDK_PYTHON"
